Feature/favourite
aagavin/APITanic pull request #25
Opened 2018-01-06 21:35 UTC by aagavin

# favourite

## This PR includes
* CRUD For favourites
* Rewrite of all features needed from the broken ID
* Frontend update

This closes issue #10, #11 and #16

2018-01-07 18:27 UTC, aramrattan requested changes
There are a few Python 3.6 features in here that are not compatible with 3.5

2018-01-07 18:27 UTC, aramrattan commented on apitanic/controller/imdb.py
> +    popular_movies_list: list = []
Python 3.5 does not support variable annotations

2018-01-07 18:27 UTC, aramrattan commented on apitanic/model/firebase.py
> +        self.favourites_ref: CollectionReference = firebase_db.collection('favourites')
variable annotation

2018-01-08 01:05 UTC, aagavin commented
Fixed

2018-01-08 01:14 UTC, aramrattan approved these changes

2018-01-08 01:15 UTC, merged